const itemsList = [
	{
		itemName: 'Oxygen',
		quantity: 32,
		state: 'Delhi',
		contact: '+91 9639287918',
		verified: '10-03-2021',
		address: 'Uphaar Cinema Complex, 1st Floor, Market S-14, Green Park Extension, Green Park, New Delhi, Delhi 110016',
	},
	{
		itemName: 'Plasma',
		quantity: 15,
		state: 'Bhopal',
		contact: '+91 8629991803',
		verified: '23-04-2021',
		address: 'RKDF Medical college Address: NH-12, Behind Vrindavan Garden, Hoshangabad Road, ,Bhopal',
	},
	{
		itemName: 'Hospital Beds',
		quantity: 4,
		state: 'Bihar',
		contact: '+91 8629991803',
		verified: null,
		address: 'RKDF Medical college Address: NH-12, Behind Vrindavan Garden, Hoshangabad Road, ,Bhopal',
	},
	{
		itemName: 'Plasma',
		quantity: 10,
		state: 'Bhopal',
		contact: '+91 8377891803',
		verified: '25-05-2021',
		address: 'Sardar Singh Memorial Hospital, Sindhi Colony, Bani Park, Jaipur',
	},
	{
		itemName: 'Oxygen',
		quantity: 32,
		state: 'Delhi',
		contact: '+91 9639287918',
		verified: '10-03-2021',
		address: 'Uphaar Cinema Complex, 1st Floor, Market S-14, Green Park Extension, Green Park, New Delhi, Delhi 110016',
	},
	{
		itemName: 'Plasma',
		quantity: 15,
		state: 'Bhopal',
		contact: '+91 8629991803',
		verified: '23-04-2021',
		address: 'RKDF Medical college Address: NH-12, Behind Vrindavan Garden, Hoshangabad Road, ,Bhopal',
	},
	{
		itemName: 'Oxygen',
		quantity: 4,
		state: 'Bihar',
		contact: '+91 8629991803',
		verified: null,
		address: 'RKDF Medical college Address: NH-12, Behind Vrindavan Garden, Hoshangabad Road, ,Bhopal',
	},
	{
		itemName: 'Plasma',
		quantity: 10,
		state: 'Bhopal',
		contact: '+91 8377891803',
		verified: '25-05-2021',
		address: 'Sardar Singh Memorial Hospital, Sindhi Colony, Bani Park, Jaipur',
	},
];

const statesList = [
	'Andaman & Nicobar',
	'Andhra Pradesh',
	'Arunachal Pradesh',
	'Assam',
	'Bihar',
	'Chandigarh',
	'Chhattisgarh',
	'Dadra & Nagar Haveli',
	'Daman & Diu',
	'Delhi',
	'Goa',
	'Gujarat',
	'Haryana',
	'Himachal Pradesh',
	'Jammu & Kashmir',
	'Jharkhand',
	'Karnataka',
	'Kerala',
	'Lakshadweep',
	'Madhya Pradesh',
	'Maharashtra',
	'Manipur',
	'Meghalaya',
	'Mizoram',
	'Nagaland',
	'Orissa',
	'Pondicherry',
	'Punjab',
	'Rajasthan',
	'Sikkim',
	'Tamil Nadu',
	'Tripura',
	'Uttar Pradesh',
	'Uttaranchal',
	'West Bengal',
];

export { itemsList, statesList };
